// KJ Motors — vehicle inventory dataset
// Vehicle photos: Unsplash (unsplash.com), used under the Unsplash License (free for commercial use).
// See credits.txt for photographer attribution per photo.
const CAR_DATA = [
  {
    "id": 1,
    "brand": "Toyota",
    "model": "Corolla",
    "name": "Toyota Corolla",
    "year": 2021,
    "origin": "Japanese",
    "category": "luxury",
    "price": 24000,
    "mileage": 35000,
    "fuel": "Diesel",
    "transmission": "Automatic",
    "condition": "Certified Pre-Owned",
    "color": "Jet Black",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1650959818516-03d68079f9a0?auto=format&fit=crop&w=800&q=75",
    "seed": "toyota1"
  },
  {
    "id": 2,
    "brand": "Toyota",
    "model": "Camry",
    "name": "Toyota Camry",
    "year": 2016,
    "origin": "Japanese",
    "category": "luxury",
    "price": 35500,
    "mileage": 17000,
    "fuel": "Petrol",
    "transmission": "Manual",
    "condition": "Used",
    "color": "Jet Black",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1614026480209-cd9934144671?auto=format&fit=crop&w=800&q=75",
    "seed": "toyota2"
  },
  {
    "id": 3,
    "brand": "Toyota",
    "model": "Supra",
    "name": "Toyota Supra",
    "year": 2024,
    "origin": "Japanese",
    "category": "sports",
    "price": 44500,
    "mileage": 2000,
    "fuel": "Hybrid",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Pearl White",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1570356528233-b442cf2de345?auto=format&fit=crop&w=800&q=75",
    "seed": "toyota3"
  },
  {
    "id": 4,
    "brand": "Toyota",
    "model": "Land Cruiser",
    "name": "Toyota Land Cruiser",
    "year": 2025,
    "origin": "Japanese",
    "category": "suv",
    "price": 42000,
    "mileage": 35000,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Storm Grey",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1612563893490-d86ed296e5e6?auto=format&fit=crop&w=800&q=75",
    "seed": "toyota4"
  },
  {
    "id": 5,
    "brand": "Toyota",
    "model": "RAV4",
    "name": "Toyota RAV4",
    "year": 2020,
    "origin": "Japanese",
    "category": "suv",
    "price": 36000,
    "mileage": 11000,
    "fuel": "Petrol",
    "transmission": "DCT (Dual-Clutch)",
    "condition": "Used",
    "color": "Storm Grey",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1654159866298-e3c8ee93e43b?auto=format&fit=crop&w=800&q=75",
    "seed": "toyota5"
  },
  {
    "id": 6,
    "brand": "Toyota",
    "model": "86",
    "name": "Toyota 86",
    "year": 2018,
    "origin": "Japanese",
    "category": "sports",
    "price": 30000,
    "mileage": 53000,
    "fuel": "Diesel",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Jet Black",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=800&q=75",
    "seed": "toyota6"
  },
  {
    "id": 7,
    "brand": "Toyota",
    "model": "Crown",
    "name": "Toyota Crown",
    "year": 2017,
    "origin": "Japanese",
    "category": "luxury",
    "price": 37500,
    "mileage": 2000,
    "fuel": "Diesel",
    "transmission": "Manual",
    "condition": "Certified Pre-Owned",
    "color": "Storm Grey",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1650959818516-03d68079f9a0?auto=format&fit=crop&w=800&q=75",
    "seed": "toyota7"
  },
  {
    "id": 8,
    "brand": "Toyota",
    "model": "Century",
    "name": "Toyota Century",
    "year": 2021,
    "origin": "Japanese",
    "category": "luxury",
    "price": 34500,
    "mileage": 53000,
    "fuel": "Petrol (Turbo)",
    "transmission": "Manual",
    "condition": "Used",
    "color": "Racing Red",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1615063029891-497bebd4f03c?auto=format&fit=crop&w=800&q=75",
    "seed": "toyota8"
  },
  {
    "id": 9,
    "brand": "Toyota",
    "model": "Prius",
    "name": "Toyota Prius",
    "year": 2019,
    "origin": "Japanese",
    "category": "luxury",
    "price": 21500,
    "mileage": 51500,
    "fuel": "Petrol",
    "transmission": "Manual",
    "condition": "Used",
    "color": "Champagne Gold",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1603189549723-29a00cd56120?auto=format&fit=crop&w=800&q=75",
    "seed": "toyota9"
  },
  {
    "id": 10,
    "brand": "Toyota",
    "model": "Hilux",
    "name": "Toyota Hilux",
    "year": 2017,
    "origin": "Japanese",
    "category": "luxury",
    "price": 23000,
    "mileage": 45500,
    "fuel": "Petrol",
    "transmission": "Manual",
    "condition": "Used",
    "color": "Champagne Gold",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1668692753102-a9603d87a1a7?auto=format&fit=crop&w=800&q=75",
    "seed": "toyota10"
  },
  {
    "id": 11,
    "brand": "Toyota",
    "model": "Yaris",
    "name": "Toyota Yaris",
    "year": 2017,
    "origin": "Japanese",
    "category": "luxury",
    "price": 44000,
    "mileage": 50000,
    "fuel": "Diesel",
    "transmission": "Manual",
    "condition": "Used",
    "color": "Silver Ice",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&w=800&q=75",
    "seed": "toyota11"
  },
  {
    "id": 12,
    "brand": "Honda",
    "model": "Civic Type R",
    "name": "Honda Civic Type R",
    "year": 2025,
    "origin": "Japanese",
    "category": "luxury",
    "price": 35000,
    "mileage": 3500,
    "fuel": "Hybrid",
    "transmission": "Manual",
    "condition": "Used",
    "color": "Jet Black",
    "featured": true,
    "image": "https://images.unsplash.com/photo-1651446404130-104e68e2f39a?auto=format&fit=crop&w=800&q=75",
    "seed": "honda12"
  },
  {
    "id": 13,
    "brand": "Honda",
    "model": "Accord",
    "name": "Honda Accord",
    "year": 2020,
    "origin": "Japanese",
    "category": "luxury",
    "price": 41000,
    "mileage": 51500,
    "fuel": "Petrol (Turbo)",
    "transmission": "Manual",
    "condition": "Used",
    "color": "British Racing Green",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=75",
    "seed": "honda13"
  },
  {
    "id": 14,
    "brand": "Honda",
    "model": "NSX",
    "name": "Honda NSX",
    "year": 2021,
    "origin": "Japanese",
    "category": "sports",
    "price": 28000,
    "mileage": 41000,
    "fuel": "Petrol",
    "transmission": "DCT (Dual-Clutch)",
    "condition": "Used",
    "color": "Champagne Gold",
    "featured": true,
    "image": "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=75",
    "seed": "honda14"
  },
  {
    "id": 15,
    "brand": "Honda",
    "model": "CR-V",
    "name": "Honda CR-V",
    "year": 2020,
    "origin": "Japanese",
    "category": "suv",
    "price": 26500,
    "mileage": 68000,
    "fuel": "Petrol",
    "transmission": "Manual",
    "condition": "Used",
    "color": "Jet Black",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=800&q=75",
    "seed": "honda15"
  },
  {
    "id": 16,
    "brand": "Honda",
    "model": "S2000",
    "name": "Honda S2000",
    "year": 2022,
    "origin": "Japanese",
    "category": "sports",
    "price": 51500,
    "mileage": 23000,
    "fuel": "Petrol (Turbo)",
    "transmission": "Manual",
    "condition": "Certified Pre-Owned",
    "color": "Deep Blue Metallic",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1493238792000-8113da705763?auto=format&fit=crop&w=800&q=75",
    "seed": "honda16"
  },
  {
    "id": 17,
    "brand": "Honda",
    "model": "Civic",
    "name": "Honda Civic",
    "year": 2021,
    "origin": "Japanese",
    "category": "luxury",
    "price": 42500,
    "mileage": 33500,
    "fuel": "Petrol (Turbo)",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Titanium Grey",
    "featured": true,
    "image": "https://images.unsplash.com/photo-1650959818516-03d68079f9a0?auto=format&fit=crop&w=800&q=75",
    "seed": "honda17"
  },
  {
    "id": 18,
    "brand": "Honda",
    "model": "Odyssey",
    "name": "Honda Odyssey",
    "year": 2019,
    "origin": "Japanese",
    "category": "luxury",
    "price": 20500,
    "mileage": 44000,
    "fuel": "Hybrid",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Deep Blue Metallic",
    "featured": true,
    "image": "https://images.unsplash.com/photo-1615063029891-497bebd4f03c?auto=format&fit=crop&w=800&q=75",
    "seed": "honda18"
  },
  {
    "id": 19,
    "brand": "Honda",
    "model": "e:Ny1",
    "name": "Honda e:Ny1",
    "year": 2022,
    "origin": "Japanese",
    "category": "luxury",
    "price": 37500,
    "mileage": 32000,
    "fuel": "Diesel",
    "transmission": "Manual",
    "condition": "Used",
    "color": "Storm Grey",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1603189549723-29a00cd56120?auto=format&fit=crop&w=800&q=75",
    "seed": "honda19"
  },
  {
    "id": 20,
    "brand": "Honda",
    "model": "HR-V",
    "name": "Honda HR-V",
    "year": 2016,
    "origin": "Japanese",
    "category": "suv",
    "price": 38500,
    "mileage": 71000,
    "fuel": "Petrol (Turbo)",
    "transmission": "DCT (Dual-Clutch)",
    "condition": "Certified Pre-Owned",
    "color": "British Racing Green",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=75",
    "seed": "honda20"
  },
  {
    "id": 21,
    "brand": "Nissan",
    "model": "GT-R",
    "name": "Nissan GT-R",
    "year": 2022,
    "origin": "Japanese",
    "category": "sports",
    "price": 29000,
    "mileage": 42500,
    "fuel": "Diesel",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Jet Black",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=75",
    "seed": "nissan21"
  },
  {
    "id": 22,
    "brand": "Nissan",
    "model": "Fairlady Z",
    "name": "Nissan Fairlady Z",
    "year": 2023,
    "origin": "Japanese",
    "category": "luxury",
    "price": 23500,
    "mileage": 8000,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Alpine White",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1650959818516-03d68079f9a0?auto=format&fit=crop&w=800&q=75",
    "seed": "nissan22"
  },
  {
    "id": 23,
    "brand": "Nissan",
    "model": "Skyline GT-R",
    "name": "Nissan Skyline GT-R",
    "year": 2024,
    "origin": "Japanese",
    "category": "sports",
    "price": 29000,
    "mileage": 32000,
    "fuel": "Diesel",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Pearl White",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1493238792000-8113da705763?auto=format&fit=crop&w=800&q=75",
    "seed": "nissan23"
  },
  {
    "id": 24,
    "brand": "Nissan",
    "model": "Patrol",
    "name": "Nissan Patrol",
    "year": 2020,
    "origin": "Japanese",
    "category": "suv",
    "price": 32500,
    "mileage": 54500,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Champagne Gold",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=75",
    "seed": "nissan24"
  },
  {
    "id": 25,
    "brand": "Nissan",
    "model": "X-Trail",
    "name": "Nissan X-Trail",
    "year": 2023,
    "origin": "Japanese",
    "category": "suv",
    "price": 37000,
    "mileage": 42500,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Silver Ice",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1618353482480-61ca5a9a7879?auto=format&fit=crop&w=800&q=75",
    "seed": "nissan25"
  },
  {
    "id": 26,
    "brand": "Nissan",
    "model": "Leaf",
    "name": "Nissan Leaf",
    "year": 2023,
    "origin": "Japanese",
    "category": "electric",
    "price": 52000,
    "mileage": 63500,
    "fuel": "Electric",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Storm Grey",
    "featured": true,
    "image": "https://images.unsplash.com/photo-1668692753102-a9603d87a1a7?auto=format&fit=crop&w=800&q=75",
    "seed": "nissan26"
  },
  {
    "id": 27,
    "brand": "Nissan",
    "model": "Silvia",
    "name": "Nissan Silvia",
    "year": 2024,
    "origin": "Japanese",
    "category": "sports",
    "price": 40500,
    "mileage": 11000,
    "fuel": "Diesel",
    "transmission": "Automatic",
    "condition": "Certified Pre-Owned",
    "color": "Deep Blue Metallic",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1612545667889-b061512d0dfa?auto=format&fit=crop&w=800&q=75",
    "seed": "nissan27"
  },
  {
    "id": 28,
    "brand": "Nissan",
    "model": "Ariya",
    "name": "Nissan Ariya",
    "year": 2017,
    "origin": "Japanese",
    "category": "electric",
    "price": 47000,
    "mileage": 21500,
    "fuel": "Electric",
    "transmission": "Automatic",
    "condition": "Certified Pre-Owned",
    "color": "Silver Ice",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1615063029891-497bebd4f03c?auto=format&fit=crop&w=800&q=75",
    "seed": "nissan28"
  },
  {
    "id": 29,
    "brand": "Nissan",
    "model": "Juke",
    "name": "Nissan Juke",
    "year": 2021,
    "origin": "Japanese",
    "category": "suv",
    "price": 47500,
    "mileage": 18500,
    "fuel": "Petrol",
    "transmission": "DCT (Dual-Clutch)",
    "condition": "Used",
    "color": "Racing Red",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1654159866298-e3c8ee93e43b?auto=format&fit=crop&w=800&q=75",
    "seed": "nissan29"
  },
  {
    "id": 30,
    "brand": "Mazda",
    "model": "MX-5 Miata",
    "name": "Mazda MX-5 Miata",
    "year": 2019,
    "origin": "Japanese",
    "category": "sports",
    "price": 36000,
    "mileage": 35000,
    "fuel": "Hybrid",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Storm Grey",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1603189617530-6d32306f57c5?auto=format&fit=crop&w=800&q=75",
    "seed": "mazda30"
  },
  {
    "id": 31,
    "brand": "Mazda",
    "model": "RX-7",
    "name": "Mazda RX-7",
    "year": 2016,
    "origin": "Japanese",
    "category": "sports",
    "price": 27000,
    "mileage": 23000,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "condition": "Certified Pre-Owned",
    "color": "Pearl White",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=75",
    "seed": "mazda31"
  },
  {
    "id": 32,
    "brand": "Mazda",
    "model": "CX-60",
    "name": "Mazda CX-60",
    "year": 2023,
    "origin": "Japanese",
    "category": "suv",
    "price": 33500,
    "mileage": 32000,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Champagne Gold",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=800&q=75",
    "seed": "mazda32"
  },
  {
    "id": 33,
    "brand": "Mazda",
    "model": "Mazda6",
    "name": "Mazda Mazda6",
    "year": 2019,
    "origin": "Japanese",
    "category": "luxury",
    "price": 35000,
    "mileage": 56000,
    "fuel": "Petrol (Turbo)",
    "transmission": "DCT (Dual-Clutch)",
    "condition": "Used",
    "color": "Champagne Gold",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=75",
    "seed": "mazda33"
  },
  {
    "id": 34,
    "brand": "Mazda",
    "model": "CX-5",
    "name": "Mazda CX-5",
    "year": 2021,
    "origin": "Japanese",
    "category": "suv",
    "price": 44000,
    "mileage": 5000,
    "fuel": "Hybrid",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Racing Red",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1618353482480-61ca5a9a7879?auto=format&fit=crop&w=800&q=75",
    "seed": "mazda34"
  },
  {
    "id": 35,
    "brand": "Mazda",
    "model": "MX-30",
    "name": "Mazda MX-30",
    "year": 2018,
    "origin": "Japanese",
    "category": "electric",
    "price": 38000,
    "mileage": 57500,
    "fuel": "Electric",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Jet Black",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1668692753102-a9603d87a1a7?auto=format&fit=crop&w=800&q=75",
    "seed": "mazda35"
  },
  {
    "id": 36,
    "brand": "Mazda",
    "model": "Mazda3",
    "name": "Mazda Mazda3",
    "year": 2022,
    "origin": "Japanese",
    "category": "luxury",
    "price": 34000,
    "mileage": 35000,
    "fuel": "Hybrid",
    "transmission": "Automatic",
    "condition": "Certified Pre-Owned",
    "color": "Titanium Grey",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1603189549723-29a00cd56120?auto=format&fit=crop&w=800&q=75",
    "seed": "mazda36"
  },
  {
    "id": 37,
    "brand": "Lexus",
    "model": "LC 500",
    "name": "Lexus LC 500",
    "year": 2018,
    "origin": "Japanese",
    "category": "luxury",
    "price": 40000,
    "mileage": 11000,
    "fuel": "Diesel",
    "transmission": "Manual",
    "condition": "Certified Pre-Owned",
    "color": "Titanium Grey",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1668692753102-a9603d87a1a7?auto=format&fit=crop&w=800&q=75",
    "seed": "lexus37"
  },
  {
    "id": 38,
    "brand": "Lexus",
    "model": "RX 350",
    "name": "Lexus RX 350",
    "year": 2025,
    "origin": "Japanese",
    "category": "luxury",
    "price": 69000,
    "mileage": 60500,
    "fuel": "Petrol (Turbo)",
    "transmission": "Automatic",
    "condition": "Certified Pre-Owned",
    "color": "Storm Grey",
    "featured": true,
    "image": "https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&w=800&q=75",
    "seed": "lexus38"
  },
  {
    "id": 39,
    "brand": "Lexus",
    "model": "LX 600",
    "name": "Lexus LX 600",
    "year": 2016,
    "origin": "Japanese",
    "category": "suv",
    "price": 99500,
    "mileage": 66500,
    "fuel": "Diesel",
    "transmission": "DCT (Dual-Clutch)",
    "condition": "Certified Pre-Owned",
    "color": "Titanium Grey",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1654159866298-e3c8ee93e43b?auto=format&fit=crop&w=800&q=75",
    "seed": "lexus39"
  },
  {
    "id": 40,
    "brand": "Lexus",
    "model": "IS 500",
    "name": "Lexus IS 500",
    "year": 2019,
    "origin": "Japanese",
    "category": "luxury",
    "price": 92000,
    "mileage": 17000,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Storm Grey",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1651446404130-104e68e2f39a?auto=format&fit=crop&w=800&q=75",
    "seed": "lexus40"
  },
  {
    "id": 41,
    "brand": "Lexus",
    "model": "ES 300h",
    "name": "Lexus ES 300h",
    "year": 2025,
    "origin": "Japanese",
    "category": "luxury",
    "price": 59500,
    "mileage": 21500,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Silver Ice",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1650959818516-03d68079f9a0?auto=format&fit=crop&w=800&q=75",
    "seed": "lexus41"
  },
  {
    "id": 42,
    "brand": "Lexus",
    "model": "LFA",
    "name": "Lexus LFA",
    "year": 2025,
    "origin": "Japanese",
    "category": "sports",
    "price": 123500,
    "mileage": 47000,
    "fuel": "Petrol",
    "transmission": "DCT (Dual-Clutch)",
    "condition": "Used",
    "color": "Storm Grey",
    "featured": true,
    "image": "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=75",
    "seed": "lexus42"
  },
  {
    "id": 43,
    "brand": "Lexus",
    "model": "UX 250h",
    "name": "Lexus UX 250h",
    "year": 2024,
    "origin": "Japanese",
    "category": "suv",
    "price": 43000,
    "mileage": 39500,
    "fuel": "Hybrid",
    "transmission": "DCT (Dual-Clutch)",
    "condition": "Used",
    "color": "Titanium Grey",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1618353482480-61ca5a9a7879?auto=format&fit=crop&w=800&q=75",
    "seed": "lexus43"
  },
  {
    "id": 44,
    "brand": "Subaru",
    "model": "WRX STI",
    "name": "Subaru WRX STI",
    "year": 2023,
    "origin": "Japanese",
    "category": "sports",
    "price": 58500,
    "mileage": 66500,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Storm Grey",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1610587144035-4ce2cefe4051?auto=format&fit=crop&w=800&q=75",
    "seed": "subaru44"
  },
  {
    "id": 45,
    "brand": "Subaru",
    "model": "BRZ",
    "name": "Subaru BRZ",
    "year": 2023,
    "origin": "Japanese",
    "category": "sports",
    "price": 35500,
    "mileage": 50000,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Alpine White",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1603189617530-6d32306f57c5?auto=format&fit=crop&w=800&q=75",
    "seed": "subaru45"
  },
  {
    "id": 46,
    "brand": "Subaru",
    "model": "Outback",
    "name": "Subaru Outback",
    "year": 2024,
    "origin": "Japanese",
    "category": "suv",
    "price": 41500,
    "mileage": 50000,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Silver Ice",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1693532331766-bfcec4163ce4?auto=format&fit=crop&w=800&q=75",
    "seed": "subaru46"
  },
  {
    "id": 47,
    "brand": "Subaru",
    "model": "Forester",
    "name": "Subaru Forester",
    "year": 2024,
    "origin": "Japanese",
    "category": "suv",
    "price": 47000,
    "mileage": 45500,
    "fuel": "Petrol",
    "transmission": "Manual",
    "condition": "Used",
    "color": "Storm Grey",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=800&q=75",
    "seed": "subaru47"
  },
  {
    "id": 48,
    "brand": "Subaru",
    "model": "Levorg",
    "name": "Subaru Levorg",
    "year": 2023,
    "origin": "Japanese",
    "category": "luxury",
    "price": 39500,
    "mileage": 20000,
    "fuel": "Diesel",
    "transmission": "Manual",
    "condition": "Certified Pre-Owned",
    "color": "Racing Red",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&w=800&q=75",
    "seed": "subaru48"
  },
  {
    "id": 49,
    "brand": "Subaru",
    "model": "Impreza",
    "name": "Subaru Impreza",
    "year": 2018,
    "origin": "Japanese",
    "category": "luxury",
    "price": 36500,
    "mileage": 8000,
    "fuel": "Petrol",
    "transmission": "Manual",
    "condition": "Used",
    "color": "Racing Red",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=800&q=75",
    "seed": "subaru49"
  },
  {
    "id": 50,
    "brand": "Mitsubishi",
    "model": "Lancer Evolution",
    "name": "Mitsubishi Lancer Evolution",
    "year": 2019,
    "origin": "Japanese",
    "category": "luxury",
    "price": 40000,
    "mileage": 26000,
    "fuel": "Hybrid",
    "transmission": "Automatic",
    "condition": "Certified Pre-Owned",
    "color": "Silver Ice",
    "featured": true,
    "image": "https://images.unsplash.com/photo-1651446404130-104e68e2f39a?auto=format&fit=crop&w=800&q=75",
    "seed": "mitsubishi50"
  },
  {
    "id": 51,
    "brand": "Mitsubishi",
    "model": "Pajero",
    "name": "Mitsubishi Pajero",
    "year": 2018,
    "origin": "Japanese",
    "category": "suv",
    "price": 36500,
    "mileage": 18500,
    "fuel": "Hybrid",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Champagne Gold",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1654159866298-e3c8ee93e43b?auto=format&fit=crop&w=800&q=75",
    "seed": "mitsubishi51"
  },
  {
    "id": 52,
    "brand": "Mitsubishi",
    "model": "Outlander",
    "name": "Mitsubishi Outlander",
    "year": 2019,
    "origin": "Japanese",
    "category": "suv",
    "price": 25500,
    "mileage": 65000,
    "fuel": "Petrol",
    "transmission": "DCT (Dual-Clutch)",
    "condition": "Used",
    "color": "Silver Ice",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=800&q=75",
    "seed": "mitsubishi52"
  },
  {
    "id": 53,
    "brand": "Mitsubishi",
    "model": "Eclipse Cross",
    "name": "Mitsubishi Eclipse Cross",
    "year": 2021,
    "origin": "Japanese",
    "category": "luxury",
    "price": 28500,
    "mileage": 5000,
    "fuel": "Hybrid",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Storm Grey",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1650959818516-03d68079f9a0?auto=format&fit=crop&w=800&q=75",
    "seed": "mitsubishi53"
  },
  {
    "id": 54,
    "brand": "Mitsubishi",
    "model": "ASX",
    "name": "Mitsubishi ASX",
    "year": 2016,
    "origin": "Japanese",
    "category": "suv",
    "price": 33500,
    "mileage": 29000,
    "fuel": "Petrol",
    "transmission": "Manual",
    "condition": "Certified Pre-Owned",
    "color": "Jet Black",
    "featured": true,
    "image": "https://images.unsplash.com/photo-1654159866298-e3c8ee93e43b?auto=format&fit=crop&w=800&q=75",
    "seed": "mitsubishi54"
  },
  {
    "id": 55,
    "brand": "Suzuki",
    "model": "Jimny",
    "name": "Suzuki Jimny",
    "year": 2019,
    "origin": "Japanese",
    "category": "suv",
    "price": 17500,
    "mileage": 5000,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Deep Blue Metallic",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=75",
    "seed": "suzuki55"
  },
  {
    "id": 56,
    "brand": "Suzuki",
    "model": "Swift Sport",
    "name": "Suzuki Swift Sport",
    "year": 2022,
    "origin": "Japanese",
    "category": "sports",
    "price": 37500,
    "mileage": 62000,
    "fuel": "Hybrid",
    "transmission": "Manual",
    "condition": "Used",
    "color": "Titanium Grey",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=75",
    "seed": "suzuki56"
  },
  {
    "id": 57,
    "brand": "Suzuki",
    "model": "Vitara",
    "name": "Suzuki Vitara",
    "year": 2024,
    "origin": "Japanese",
    "category": "suv",
    "price": 25500,
    "mileage": 44000,
    "fuel": "Hybrid",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Alpine White",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1654159866298-e3c8ee93e43b?auto=format&fit=crop&w=800&q=75",
    "seed": "suzuki57"
  },
  {
    "id": 58,
    "brand": "Suzuki",
    "model": "Swift",
    "name": "Suzuki Swift",
    "year": 2018,
    "origin": "Japanese",
    "category": "luxury",
    "price": 21000,
    "mileage": 3500,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "condition": "Certified Pre-Owned",
    "color": "Jet Black",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1567808291548-fc3ee04dbcf0?auto=format&fit=crop&w=800&q=75",
    "seed": "suzuki58"
  },
  {
    "id": 59,
    "brand": "Infiniti",
    "model": "Q60",
    "name": "Infiniti Q60",
    "year": 2017,
    "origin": "Japanese",
    "category": "luxury",
    "price": 48500,
    "mileage": 3500,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Alpine White",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1651446404130-104e68e2f39a?auto=format&fit=crop&w=800&q=75",
    "seed": "infiniti59"
  },
  {
    "id": 60,
    "brand": "Infiniti",
    "model": "QX80",
    "name": "Infiniti QX80",
    "year": 2024,
    "origin": "Japanese",
    "category": "suv",
    "price": 67500,
    "mileage": 23000,
    "fuel": "Diesel",
    "transmission": "Automatic",
    "condition": "Certified Pre-Owned",
    "color": "Racing Red",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1612563893490-d86ed296e5e6?auto=format&fit=crop&w=800&q=75",
    "seed": "infiniti60"
  },
  {
    "id": 61,
    "brand": "Infiniti",
    "model": "Q50",
    "name": "Infiniti Q50",
    "year": 2018,
    "origin": "Japanese",
    "category": "luxury",
    "price": 51000,
    "mileage": 2000,
    "fuel": "Petrol",
    "transmission": "Manual",
    "condition": "Certified Pre-Owned",
    "color": "Deep Blue Metallic",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=800&q=75",
    "seed": "infiniti61"
  },
  {
    "id": 62,
    "brand": "Acura",
    "model": "NSX",
    "name": "Acura NSX",
    "year": 2019,
    "origin": "Japanese",
    "category": "sports",
    "price": 69000,
    "mileage": 39500,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Silver Ice",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=75",
    "seed": "acura62"
  },
  {
    "id": 63,
    "brand": "Acura",
    "model": "MDX",
    "name": "Acura MDX",
    "year": 2020,
    "origin": "Japanese",
    "category": "suv",
    "price": 38000,
    "mileage": 0,
    "fuel": "Petrol",
    "transmission": "DCT (Dual-Clutch)",
    "condition": "New",
    "color": "Storm Grey",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=75",
    "seed": "acura63"
  },
  {
    "id": 64,
    "brand": "Acura",
    "model": "Integra Type S",
    "name": "Acura Integra Type S",
    "year": 2024,
    "origin": "Japanese",
    "category": "luxury",
    "price": 63000,
    "mileage": 20000,
    "fuel": "Petrol (Turbo)",
    "transmission": "Automatic",
    "condition": "Certified Pre-Owned",
    "color": "British Racing Green",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&w=800&q=75",
    "seed": "acura64"
  },
  {
    "id": 65,
    "brand": "BMW",
    "model": "M3 Competition",
    "name": "BMW M3 Competition",
    "year": 2024,
    "origin": "German",
    "category": "sports",
    "price": 115500,
    "mileage": 45500,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Silver Ice",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1610587144035-4ce2cefe4051?auto=format&fit=crop&w=800&q=75",
    "seed": "bmw65"
  },
  {
    "id": 66,
    "brand": "BMW",
    "model": "M4",
    "name": "BMW M4",
    "year": 2018,
    "origin": "German",
    "category": "sports",
    "price": 117500,
    "mileage": 30500,
    "fuel": "Petrol (Turbo)",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Jet Black",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=800&q=75",
    "seed": "bmw66"
  },
  {
    "id": 67,
    "brand": "BMW",
    "model": "i4",
    "name": "BMW i4",
    "year": 2020,
    "origin": "German",
    "category": "electric",
    "price": 104000,
    "mileage": 12500,
    "fuel": "Electric",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Jet Black",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1651446404130-104e68e2f39a?auto=format&fit=crop&w=800&q=75",
    "seed": "bmw67"
  },
  {
    "id": 68,
    "brand": "BMW",
    "model": "X5",
    "name": "BMW X5",
    "year": 2022,
    "origin": "German",
    "category": "suv",
    "price": 110500,
    "mileage": 60500,
    "fuel": "Petrol (Turbo)",
    "transmission": "DCT (Dual-Clutch)",
    "condition": "Used",
    "color": "Deep Blue Metallic",
    "featured": true,
    "image": "https://images.unsplash.com/photo-1612563893490-d86ed296e5e6?auto=format&fit=crop&w=800&q=75",
    "seed": "bmw68"
  },
  {
    "id": 69,
    "brand": "BMW",
    "model": "3 Series",
    "name": "BMW 3 Series",
    "year": 2018,
    "origin": "German",
    "category": "luxury",
    "price": 54500,
    "mileage": 23000,
    "fuel": "Petrol",
    "transmission": "Manual",
    "condition": "Used",
    "color": "Silver Ice",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1567808291548-fc3ee04dbcf0?auto=format&fit=crop&w=800&q=75",
    "seed": "bmw69"
  },
  {
    "id": 70,
    "brand": "BMW",
    "model": "7 Series",
    "name": "BMW 7 Series",
    "year": 2024,
    "origin": "German",
    "category": "luxury",
    "price": 76500,
    "mileage": 20000,
    "fuel": "Petrol",
    "transmission": "Manual",
    "condition": "Used",
    "color": "Silver Ice",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1603189549723-29a00cd56120?auto=format&fit=crop&w=800&q=75",
    "seed": "bmw70"
  },
  {
    "id": 71,
    "brand": "BMW",
    "model": "Z4",
    "name": "BMW Z4",
    "year": 2021,
    "origin": "German",
    "category": "sports",
    "price": 113500,
    "mileage": 5000,
    "fuel": "Petrol",
    "transmission": "DCT (Dual-Clutch)",
    "condition": "Certified Pre-Owned",
    "color": "Racing Red",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1607853554439-0069ec0f29b6?auto=format&fit=crop&w=800&q=75",
    "seed": "bmw71"
  },
  {
    "id": 72,
    "brand": "BMW",
    "model": "iX",
    "name": "BMW iX",
    "year": 2016,
    "origin": "German",
    "category": "electric",
    "price": 53000,
    "mileage": 21500,
    "fuel": "Electric",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Titanium Grey",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1668692753102-a9603d87a1a7?auto=format&fit=crop&w=800&q=75",
    "seed": "bmw72"
  },
  {
    "id": 73,
    "brand": "BMW",
    "model": "M5",
    "name": "BMW M5",
    "year": 2016,
    "origin": "German",
    "category": "sports",
    "price": 115500,
    "mileage": 0,
    "fuel": "Petrol",
    "transmission": "DCT (Dual-Clutch)",
    "condition": "New",
    "color": "Racing Red",
    "featured": true,
    "image": "https://images.unsplash.com/photo-1607853554439-0069ec0f29b6?auto=format&fit=crop&w=800&q=75",
    "seed": "bmw73"
  },
  {
    "id": 74,
    "brand": "BMW",
    "model": "X3",
    "name": "BMW X3",
    "year": 2024,
    "origin": "German",
    "category": "suv",
    "price": 60000,
    "mileage": 60500,
    "fuel": "Petrol (Turbo)",
    "transmission": "DCT (Dual-Clutch)",
    "condition": "Used",
    "color": "Silver Ice",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1612563893490-d86ed296e5e6?auto=format&fit=crop&w=800&q=75",
    "seed": "bmw74"
  },
  {
    "id": 75,
    "brand": "BMW",
    "model": "1 Series",
    "name": "BMW 1 Series",
    "year": 2023,
    "origin": "German",
    "category": "luxury",
    "price": 53500,
    "mileage": 24500,
    "fuel": "Hybrid",
    "transmission": "DCT (Dual-Clutch)",
    "condition": "Used",
    "color": "Alpine White",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1615063029891-497bebd4f03c?auto=format&fit=crop&w=800&q=75",
    "seed": "bmw75"
  },
  {
    "id": 76,
    "brand": "Mercedes-Benz",
    "model": "AMG GT",
    "name": "Mercedes-Benz AMG GT",
    "year": 2024,
    "origin": "German",
    "category": "sports",
    "price": 159500,
    "mileage": 38000,
    "fuel": "Hybrid",
    "transmission": "DCT (Dual-Clutch)",
    "condition": "Used",
    "color": "Storm Grey",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=800&q=75",
    "seed": "mercedesbenz76"
  },
  {
    "id": 77,
    "brand": "Mercedes-Benz",
    "model": "S-Class",
    "name": "Mercedes-Benz S-Class",
    "year": 2025,
    "origin": "German",
    "category": "luxury",
    "price": 145500,
    "mileage": 0,
    "fuel": "Hybrid",
    "transmission": "DCT (Dual-Clutch)",
    "condition": "New",
    "color": "Racing Red",
    "featured": true,
    "image": "https://images.unsplash.com/photo-1651446404130-104e68e2f39a?auto=format&fit=crop&w=800&q=75",
    "seed": "mercedesbenz77"
  },
  {
    "id": 78,
    "brand": "Mercedes-Benz",
    "model": "G-Wagon G63",
    "name": "Mercedes-Benz G-Wagon G63",
    "year": 2016,
    "origin": "German",
    "category": "suv",
    "price": 59000,
    "mileage": 57500,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Champagne Gold",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1693532331766-bfcec4163ce4?auto=format&fit=crop&w=800&q=75",
    "seed": "mercedesbenz78"
  },
  {
    "id": 79,
    "brand": "Mercedes-Benz",
    "model": "C-Class",
    "name": "Mercedes-Benz C-Class",
    "year": 2016,
    "origin": "German",
    "category": "luxury",
    "price": 118000,
    "mileage": 48500,
    "fuel": "Diesel",
    "transmission": "Manual",
    "condition": "Used",
    "color": "Alpine White",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=800&q=75",
    "seed": "mercedesbenz79"
  },
  {
    "id": 80,
    "brand": "Mercedes-Benz",
    "model": "EQS",
    "name": "Mercedes-Benz EQS",
    "year": 2017,
    "origin": "German",
    "category": "electric",
    "price": 154000,
    "mileage": 45500,
    "fuel": "Electric",
    "transmission": "Automatic",
    "condition": "Certified Pre-Owned",
    "color": "Jet Black",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1651446404130-104e68e2f39a?auto=format&fit=crop&w=800&q=75",
    "seed": "mercedesbenz80"
  },
  {
    "id": 81,
    "brand": "Mercedes-Benz",
    "model": "GLE",
    "name": "Mercedes-Benz GLE",
    "year": 2017,
    "origin": "German",
    "category": "suv",
    "price": 147000,
    "mileage": 68000,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Racing Red",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=75",
    "seed": "mercedesbenz81"
  },
  {
    "id": 82,
    "brand": "Mercedes-Benz",
    "model": "SL 63 AMG",
    "name": "Mercedes-Benz SL 63 AMG",
    "year": 2019,
    "origin": "German",
    "category": "sports",
    "price": 89500,
    "mileage": 68000,
    "fuel": "Diesel",
    "transmission": "Manual",
    "condition": "Used",
    "color": "British Racing Green",
    "featured": true,
    "image": "https://images.unsplash.com/photo-1607853554439-0069ec0f29b6?auto=format&fit=crop&w=800&q=75",
    "seed": "mercedesbenz82"
  },
  {
    "id": 83,
    "brand": "Mercedes-Benz",
    "model": "A-Class",
    "name": "Mercedes-Benz A-Class",
    "year": 2020,
    "origin": "German",
    "category": "luxury",
    "price": 136500,
    "mileage": 0,
    "fuel": "Diesel",
    "transmission": "DCT (Dual-Clutch)",
    "condition": "New",
    "color": "Racing Red",
    "featured": true,
    "image": "https://images.unsplash.com/photo-1603189549723-29a00cd56120?auto=format&fit=crop&w=800&q=75",
    "seed": "mercedesbenz83"
  },
  {
    "id": 84,
    "brand": "Mercedes-Benz",
    "model": "CLA",
    "name": "Mercedes-Benz CLA",
    "year": 2018,
    "origin": "German",
    "category": "luxury",
    "price": 79500,
    "mileage": 21500,
    "fuel": "Diesel",
    "transmission": "DCT (Dual-Clutch)",
    "condition": "Used",
    "color": "Pearl White",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1567808291548-fc3ee04dbcf0?auto=format&fit=crop&w=800&q=75",
    "seed": "mercedesbenz84"
  },
  {
    "id": 85,
    "brand": "Audi",
    "model": "RS6 Avant",
    "name": "Audi RS6 Avant",
    "year": 2016,
    "origin": "German",
    "category": "sports",
    "price": 130000,
    "mileage": 2000,
    "fuel": "Petrol",
    "transmission": "DCT (Dual-Clutch)",
    "condition": "Used",
    "color": "Racing Red",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=800&q=75",
    "seed": "audi85"
  },
  {
    "id": 86,
    "brand": "Audi",
    "model": "A4",
    "name": "Audi A4",
    "year": 2020,
    "origin": "German",
    "category": "luxury",
    "price": 126000,
    "mileage": 47000,
    "fuel": "Petrol",
    "transmission": "Manual",
    "condition": "Used",
    "color": "Jet Black",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1650959818516-03d68079f9a0?auto=format&fit=crop&w=800&q=75",
    "seed": "audi86"
  },
  {
    "id": 87,
    "brand": "Audi",
    "model": "Q7",
    "name": "Audi Q7",
    "year": 2024,
    "origin": "German",
    "category": "suv",
    "price": 65000,
    "mileage": 26000,
    "fuel": "Petrol (Turbo)",
    "transmission": "Manual",
    "condition": "Used",
    "color": "Deep Blue Metallic",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1693532331766-bfcec4163ce4?auto=format&fit=crop&w=800&q=75",
    "seed": "audi87"
  },
  {
    "id": 88,
    "brand": "Audi",
    "model": "R8",
    "name": "Audi R8",
    "year": 2024,
    "origin": "German",
    "category": "sports",
    "price": 124000,
    "mileage": 23000,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Pearl White",
    "featured": true,
    "image": "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=800&q=75",
    "seed": "audi88"
  },
  {
    "id": 89,
    "brand": "Audi",
    "model": "e-tron GT",
    "name": "Audi e-tron GT",
    "year": 2024,
    "origin": "German",
    "category": "electric",
    "price": 77500,
    "mileage": 32000,
    "fuel": "Electric",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Pearl White",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1692061157268-b128a8f37d6d?auto=format&fit=crop&w=800&q=75",
    "seed": "audi89"
  },
  {
    "id": 90,
    "brand": "Audi",
    "model": "TT RS",
    "name": "Audi TT RS",
    "year": 2024,
    "origin": "German",
    "category": "sports",
    "price": 94000,
    "mileage": 8000,
    "fuel": "Hybrid",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Champagne Gold",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1493238792000-8113da705763?auto=format&fit=crop&w=800&q=75",
    "seed": "audi90"
  },
  {
    "id": 91,
    "brand": "Audi",
    "model": "A8",
    "name": "Audi A8",
    "year": 2018,
    "origin": "German",
    "category": "luxury",
    "price": 33500,
    "mileage": 44000,
    "fuel": "Diesel",
    "transmission": "Manual",
    "condition": "Used",
    "color": "Titanium Grey",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1614026480209-cd9934144671?auto=format&fit=crop&w=800&q=75",
    "seed": "audi91"
  },
  {
    "id": 92,
    "brand": "Audi",
    "model": "Q8",
    "name": "Audi Q8",
    "year": 2022,
    "origin": "German",
    "category": "suv",
    "price": 82000,
    "mileage": 8000,
    "fuel": "Hybrid",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Silver Ice",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1612563893490-d86ed296e5e6?auto=format&fit=crop&w=800&q=75",
    "seed": "audi92"
  },
  {
    "id": 93,
    "brand": "Audi",
    "model": "A3",
    "name": "Audi A3",
    "year": 2017,
    "origin": "German",
    "category": "luxury",
    "price": 58500,
    "mileage": 65000,
    "fuel": "Petrol",
    "transmission": "DCT (Dual-Clutch)",
    "condition": "Used",
    "color": "Deep Blue Metallic",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1615063029891-497bebd4f03c?auto=format&fit=crop&w=800&q=75",
    "seed": "audi93"
  },
  {
    "id": 94,
    "brand": "Volkswagen",
    "model": "Golf GTI",
    "name": "Volkswagen Golf GTI",
    "year": 2022,
    "origin": "German",
    "category": "sports",
    "price": 45500,
    "mileage": 53000,
    "fuel": "Petrol",
    "transmission": "Manual",
    "condition": "Used",
    "color": "Alpine White",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=800&q=75",
    "seed": "volkswagen94"
  },
  {
    "id": 95,
    "brand": "Volkswagen",
    "model": "Tiguan",
    "name": "Volkswagen Tiguan",
    "year": 2016,
    "origin": "German",
    "category": "suv",
    "price": 53000,
    "mileage": 60500,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Deep Blue Metallic",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1693532331766-bfcec4163ce4?auto=format&fit=crop&w=800&q=75",
    "seed": "volkswagen95"
  },
  {
    "id": 96,
    "brand": "Volkswagen",
    "model": "Touareg",
    "name": "Volkswagen Touareg",
    "year": 2021,
    "origin": "German",
    "category": "suv",
    "price": 30000,
    "mileage": 71000,
    "fuel": "Petrol",
    "transmission": "Manual",
    "condition": "Used",
    "color": "British Racing Green",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=800&q=75",
    "seed": "volkswagen96"
  },
  {
    "id": 97,
    "brand": "Volkswagen",
    "model": "ID.4",
    "name": "Volkswagen ID.4",
    "year": 2024,
    "origin": "German",
    "category": "electric",
    "price": 45000,
    "mileage": 17000,
    "fuel": "Electric",
    "transmission": "Automatic",
    "condition": "Certified Pre-Owned",
    "color": "Jet Black",
    "featured": true,
    "image": "https://images.unsplash.com/photo-1651446404130-104e68e2f39a?auto=format&fit=crop&w=800&q=75",
    "seed": "volkswagen97"
  },
  {
    "id": 98,
    "brand": "Volkswagen",
    "model": "Passat",
    "name": "Volkswagen Passat",
    "year": 2022,
    "origin": "German",
    "category": "luxury",
    "price": 36000,
    "mileage": 56000,
    "fuel": "Hybrid",
    "transmission": "DCT (Dual-Clutch)",
    "condition": "Used",
    "color": "Champagne Gold",
    "featured": true,
    "image": "https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&w=800&q=75",
    "seed": "volkswagen98"
  },
  {
    "id": 99,
    "brand": "Volkswagen",
    "model": "Arteon",
    "name": "Volkswagen Arteon",
    "year": 2024,
    "origin": "German",
    "category": "luxury",
    "price": 25000,
    "mileage": 12500,
    "fuel": "Petrol",
    "transmission": "Manual",
    "condition": "Used",
    "color": "Deep Blue Metallic",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1614026480209-cd9934144671?auto=format&fit=crop&w=800&q=75",
    "seed": "volkswagen99"
  },
  {
    "id": 100,
    "brand": "Volkswagen",
    "model": "Polo",
    "name": "Volkswagen Polo",
    "year": 2020,
    "origin": "German",
    "category": "luxury",
    "price": 34500,
    "mileage": 59000,
    "fuel": "Petrol",
    "transmission": "Manual",
    "condition": "Certified Pre-Owned",
    "color": "British Racing Green",
    "featured": true,
    "image": "https://images.unsplash.com/photo-1650959818516-03d68079f9a0?auto=format&fit=crop&w=800&q=75",
    "seed": "volkswagen100"
  },
  {
    "id": 101,
    "brand": "Porsche",
    "model": "911 Turbo S",
    "name": "Porsche 911 Turbo S",
    "year": 2018,
    "origin": "German",
    "category": "sports",
    "price": 101000,
    "mileage": 17000,
    "fuel": "Petrol",
    "transmission": "Manual",
    "condition": "Certified Pre-Owned",
    "color": "Racing Red",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=800&q=75",
    "seed": "porsche101"
  },
  {
    "id": 102,
    "brand": "Porsche",
    "model": "Cayenne",
    "name": "Porsche Cayenne",
    "year": 2021,
    "origin": "German",
    "category": "suv",
    "price": 190000,
    "mileage": 38000,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Jet Black",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=800&q=75",
    "seed": "porsche102"
  },
  {
    "id": 103,
    "brand": "Porsche",
    "model": "Panamera",
    "name": "Porsche Panamera",
    "year": 2024,
    "origin": "German",
    "category": "luxury",
    "price": 79000,
    "mileage": 27500,
    "fuel": "Petrol",
    "transmission": "Manual",
    "condition": "Certified Pre-Owned",
    "color": "Racing Red",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1614026480209-cd9934144671?auto=format&fit=crop&w=800&q=75",
    "seed": "porsche103"
  },
  {
    "id": 104,
    "brand": "Porsche",
    "model": "Taycan",
    "name": "Porsche Taycan",
    "year": 2022,
    "origin": "German",
    "category": "electric",
    "price": 178500,
    "mileage": 36500,
    "fuel": "Electric",
    "transmission": "Automatic",
    "condition": "Certified Pre-Owned",
    "color": "Storm Grey",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1668692753102-a9603d87a1a7?auto=format&fit=crop&w=800&q=75",
    "seed": "porsche104"
  },
  {
    "id": 105,
    "brand": "Porsche",
    "model": "718 Cayman",
    "name": "Porsche 718 Cayman",
    "year": 2020,
    "origin": "German",
    "category": "luxury",
    "price": 143500,
    "mileage": 69500,
    "fuel": "Petrol",
    "transmission": "Manual",
    "condition": "Certified Pre-Owned",
    "color": "Silver Ice",
    "featured": true,
    "image": "https://images.unsplash.com/photo-1668692753102-a9603d87a1a7?auto=format&fit=crop&w=800&q=75",
    "seed": "porsche105"
  },
  {
    "id": 106,
    "brand": "Porsche",
    "model": "Macan",
    "name": "Porsche Macan",
    "year": 2024,
    "origin": "German",
    "category": "suv",
    "price": 213000,
    "mileage": 57500,
    "fuel": "Hybrid",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Deep Blue Metallic",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1654159866298-e3c8ee93e43b?auto=format&fit=crop&w=800&q=75",
    "seed": "porsche106"
  },
  {
    "id": 107,
    "brand": "Opel",
    "model": "Insignia",
    "name": "Opel Insignia",
    "year": 2022,
    "origin": "German",
    "category": "luxury",
    "price": 23500,
    "mileage": 59000,
    "fuel": "Petrol",
    "transmission": "Manual",
    "condition": "Used",
    "color": "Titanium Grey",
    "featured": true,
    "image": "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=75",
    "seed": "opel107"
  },
  {
    "id": 108,
    "brand": "Opel",
    "model": "Astra GSi",
    "name": "Opel Astra GSi",
    "year": 2023,
    "origin": "German",
    "category": "sports",
    "price": 44500,
    "mileage": 53000,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "condition": "Used",
    "color": "Storm Grey",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1607853554439-0069ec0f29b6?auto=format&fit=crop&w=800&q=75",
    "seed": "opel108"
  },
  {
    "id": 109,
    "brand": "Opel",
    "model": "Corsa",
    "name": "Opel Corsa",
    "year": 2023,
    "origin": "German",
    "category": "luxury",
    "price": 21000,
    "mileage": 6500,
    "fuel": "Petrol",
    "transmission": "Automatic",
    "condition": "Certified Pre-Owned",
    "color": "Jet Black",
    "featured": false,
    "image": "https://images.unsplash.com/photo-1603189549723-29a00cd56120?auto=format&fit=crop&w=800&q=75",
    "seed": "opel109"
  }
];
